# Generated by Django 2.2 on 2020-03-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mypics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mypic1', models.FileField(upload_to='')),
                ('Mypic2', models.FileField(upload_to='')),
                ('Mypic3', models.FileField(upload_to='')),
                ('Mypic4', models.FileField(upload_to='')),
                ('Mypic5', models.FileField(upload_to='')),
                ('Mypic6', models.FileField(upload_to='')),
                ('Mypic7', models.FileField(upload_to='')),
                ('Mypic8', models.FileField(upload_to='')),
                ('Mypic9', models.FileField(upload_to='')),
                ('Mypic10', models.FileField(upload_to='')),
                ('Mypic11', models.FileField(upload_to='')),
                ('Mypic12', models.FileField(upload_to='')),
                ('Mypic13', models.FileField(upload_to='')),
            ],
        ),
    ]
